### PR TITLE
Add arm64 image

### PR DESCRIPTION
**Pull request by Niek**
This PR adds arm64 arch builds.

### CODE REVIEW

**Comment by pimterry** [comment]
Oh neat! I guess this is the fix for https://github.com/httptoolkit/httptoolkit/issues/423?

Makes sense, I'm actually impressed cross-platform docker builds on GHA is so easy. Does this fix the issue for you testing locally?

**Comment by Niek** [comment]
I honestly unsure if it fixes the issue I was having in https://github.com/httptoolkit/httptoolkit/issues/423, I haven't checked. But my Docker daemon is showing warnings because the amd64 image is running in emulation, so it certainly would help to have a native image.

**Comment by pimterry** [comment]
I've just pushed this as a new v1.2.0 release. @Niek it'd be great if you could manually pull that new version from docker hub and check this is now working without warnings for you, and whether or not this does fix the other issue.

**Comment by Niek** [comment]
@pimterry Running the container manually (`docker run --rm --name=httptoolkit-docker-tunnel -p 127.0.0.1:1080:1080 ghcr.io/httptoolkit/docker-socks-tunnel`) shows that it's working fine, as does a `curl -x socks5://127.0.0.1:1080` request. I'm not sure how to force HTTP Toolkit to use `v1.2.0` though, it keeps spawning `v1.1.0`. Is there a way to force it to use the new container?

**Comment by pimterry** [comment]
Ok, great, that's a very good sign at least that the image itself works.

The server depends explicitly on a specific version (currently v1.1.0) and only moves to new versions when it's updated. You can probably work around that though by removing the real v1.1.0 and then retagging v1.2.0 as v1.1.0 on your machine locally. If there's already an existing v1.1.0 image it won't try to change it, it'll just use it as-is.

**Comment by Niek** [comment]
This did the job indeed:
```bash
docker pull httptoolkit/docker-socks-tunnel:v1.2.0
docker tag httptoolkit/docker-socks-tunnel:v1.2.0 httptoolkit/docker-socks-tunnel:v1.1.0
```

Unfortunately the issue in https://github.com/httptoolkit/httptoolkit/issues/423 is still here.

**Pull request merged**
